```{r}
library(sf)
library(tmap)
library(tidyverse)
library(ggunc)

Sys.setenv("PROJ_LIB"="/Users/mwbc/Library/Caches/org.R-project.R/R/renv/cache/v5/macos/R-4.5/aarch64-apple-darwin20/sf/1.0-23/ce0c8d7dc7715a383d874eb5be01edd5/sf/proj")

DATA_PATH = Sys.getenv("DATA_PATH")
```

```{r}
network = read_sf(file.path(DATA_PATH, "data", "graph_orig.gpkg"))
```

Condense to just a local area

```{r}
loc = tribble(
    ~lat, ~lon,
    35.96522341631404, -78.80906790134905
) |>
    st_as_sf(coords=c("lon", "lat"), crs=4326) |>
    st_transform(32119)
```

```{r}
local_network = network |>
    filter(lengths(st_intersects(geom, st_buffer(loc, 2000))) > 0)
```

```{r}
netmap = tm_basemap(server="Esri.WorldImagery") +
    tm_shape(st_buffer(loc, 500)) +
    tm_shape(local_network) +
    tm_lines(col="yellow", lwd=3) +
    tm_scalebar() +
    tm_credits("Data © Esri, NC CGIA, Vantor, OpenStreetMap", position=tm_pos_out("center", "bottom"))

tmap_save(netmap, here::here("paper/figures/network.png"), width=8, height=6, bg="white")
```

```{r}
```